### ISSUE TITLE
Gigabot XLT - GB4 #969 -- Error Message

### ISSUE THREAD

**Issue by re3Dprinting** [re3Dprinting/klipper_config#19]
Gigabot XLT - GB4 #969 -- Error Message --- 4/28/2023 8:54:11

Mainsail Version: v2.3.0-beta1
Moonraker Version: v0.7.1-453-gee312ee
Klipper Version: v0.10.0-297-gdeeb1af3

Issue Condition: Command Sent

Issue Details: After running the PID tuning command, I tried to save the values to the configuration file by using the "SAVE_CONFIG" command.  But I got an error (shown in screenshot) and the machine did not reboot or appear to save the new PID parameters.

Photos: 
https://drive.google.com/open?id=1iMq7szIvA7f9GeCSahq4RyzsgWRCg9Xl

Log Files:

**Comment by re3Dev** [comment]
Need Klippy log file to verify what the 'SAVE_CONFIG' command is doing on the command line. 

By default the command is actually doing this in the background: 
SAVE_CONFIG to '/home/pi/klipper_config/printer.cfg' (backup in '/home/pi/klipper_config/printer-20221224_213245.cfg').

Assuming above is correct, our file structure is setup to include the associated build in the printer.cfg file instead of values being declared directly. So adding new values in printer.cfg will conflict with the values in the build directory.

**Comment by re3Dev** [comment]
You can only use SAVE_CONFIG to change values in [printer.cfg] and not in any [included.cfg]. Update the values manually in [standalone.cfg].
